Initial Swagger client generator
rbkmoney/swagger-codegen pull request #13
Opened 2016-10-26 16:53 UTC by manikdv

Work in progress

2016-11-07 12:41 UTC, galaxie requested changes

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ErlangClientCodegen.java
> +            LOGGER.warn(operationId + " (reserved word) cannot be used as method name. Renamed to " + camelize(sanitizeName("call_" + operationId)));
It looks like this log message is trying to lie to me. OperationId is going to be `underscore` after all.

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/api.mustache
> +  {ok, Code, RespHeaders, ClientRef}.
It looks like this line can be deleted

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/app.src.mustache
> +        jsx,
Wrong comma

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/utils.mustache
> +-module(utils).
We still need a prefix here

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api.mustache
> +    swagger_client_api_procession:process_request(
I don't think that hardcoding prefix in a template is a good idea

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +-type state() :: state().
Will it compile?

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +-spec process_request(Method::atom(), OperationID::atom(), Url::string(), Params::map()) ->
I would suggest to export `operation_id` type and use always use it

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +    {ok, integer(), list(), {ok, binary()}}.
Please consider adding some explanations for this values.

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +    #{} = PreparedQueryParams,
Why do we have to check it here?

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +-spec handle_request_json(term(), state()) -> {ok, map(), map(), map(), map()} | {error, term()}.
This function actually never returns `{ok, ...}`

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +-spec handle_request_json(term(), state()) -> {ok, map(), map(), map(), map()} | {error, term()}.
I would add some names to these `term()`, `map()`

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +    {ok, Params :: map()} |
It looks like this `Params` is more then just a map, but a map with a specific set of keys (e.g. `qs_val`). How about describing it somewhere?

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +    Value = Body,
Looks a bit useless, but who am I to judge

2016-11-07 12:41 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_validation.mustache
> +    auth_context => AuthContext :: swagger_auth:context(),
Where did `swagger_auth` come from?

2016-11-08 16:05 UTC, galaxie requested changes

2016-11-08 16:05 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +            % populate_request_params(OperationID, T, genlib_map:deepput({{packageName}}_client_api_utils:to_binary(K), V, RequestParams), ValidatorState);
I would do something with this commented string (like remove?)

2016-11-08 16:05 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +    {UrlParams::map(), HeaderParams::map(), BodyParams::map(), QueryParams::map()} | {error, term()}.
I would recommend to use `{ok, ....} | {error, ...}` response or `term() | no_return()`

2016-11-08 16:05 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api.mustache
> +    {ok, integer(), list(), {ok, binary()}}.
Any comments about these `integer()`, `list()` etc?

2016-11-08 16:05 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_procession.mustache
> +            % populate_request_params(OperationID, T, genlib_map:deepput({{packageName}}_client_api_utils:to_binary(K), V, RequestParams), ValidatorState);
How about removing it?

2016-11-08 17:20 UTC, galaxie approved these changes
:shipit:

2016-11-08 18:01 UTC, keynslug commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_validation.mustache
> +    required |
Тут спека тогда кривая, но это и в `erlang-server` так, возможно стоит и там поправить в рамках мини-pr.

2016-11-08 18:01 UTC, keynslug commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_validation.mustache
> +-module({{packageName}}_client_api_validation).
А можно ли переиспользовать шаблоны от других таргетов, чтобы не копипастить?

2016-11-09 10:29 UTC, manikdv commented on modules/swagger-codegen/src/main/resources/erlang-client/client_api_validation.mustache
> +    required |
👍 Сделаю в виде отдельного pr

2016-11-09 11:33 UTC, merged