CAPI-72 Add date/date-time validation. Add human readable error messages
rbkmoney/swagger-codegen pull request #27
Opened 2017-03-09 16:10 UTC by galaxie

2017-03-13 15:35 UTC, arentrue requested changes
В целом валидация, на мой взгляд, несколько неудобно разбросана между `api` и `validator`.
Кроме того, не уверен, что все обновления синхронизированы между клиентской и серверной частями приложения.

2017-03-13 15:35 UTC, arentrue commented on modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ErlangClientCodegen.java
> +        supportingFiles.add(new SupportingFile("rebar.config.mustache","", "rebar.config"));
А зачем?

1. Генерённый клиент сейчас - даже не erlang либа, а просто набор erlang исходников для добавления в src целевого erlang приложения. Соответственно, даже app.src файла нет, куда уж там rebar.config.
2. Текущему rebar.config, как минимум, не хватает jesse.

Т.е. тут, по моему, надо либо делать нормальный erlang lib с app.src и rebar.config, либо забить пока и не путать никого неполноценным rebar.config.

2017-03-13 15:35 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +                <<"errorType">> => swagger_utils:to_binary(Type),
А модуль всегда будет называться swagger_utils? Тут же везде {{усатые}} имена модулей используются или так больше не модно?

2017-03-13 15:35 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/validator.mustache
> +-type validator() :: fun((json(), defname()) -> ok | {error, {{packageName}}_api:validation_error() | unavailable}).
Какая-то путаница с типами тут.
```erlang
-spec get_validator(ID :: atom()) ->
    validator().

get_validator(ID) ->
    PoolName = construct_pool_name(ID),
    fun (Json, Defname) ->
        validate_(PoolName, Json, Defname)
    end.
```
Для `validate_/3` spec'а нет, но есть
```erlang
-spec validate(ID :: atom(), json(), defname()) ->
    ok | {error, [validate_error()] | unavailable}.

validate(ID, Json, Defname) ->
    validate_(construct_pool_name(ID), Json, Defname).
```

Оставить бы только один тип `validator()` и в get_validator отдавать
```erlang
fun (Json, Defname) -> validate(ID, Json, Defname) end.
```

2017-03-13 15:35 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +-type rule() ::
А симметричные изменения в `client_api_validation.mustache` не нужны?

2017-03-14 11:05 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/validator.mustache
> +-type validator() :: fun((json(), defname()) -> ok | {error, {{packageName}}_api:validation_error() | unavailable}).
Немного поправлю себя:
`validate_error()` и `validator()`, разумеется, разные, не заменяющие друг друга типы. Проблема в том, что тип `validator:validator()` используeт `api:validation_error()` и при этом сам используется в `api` модуле. Получаем циклическую зависимость по типам, сложную для восприятия и поддержки.

2017-03-14 11:51 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +                <<"errorType">> => swagger_utils:to_binary(Type),
Это я в самый последний момент скопипастил и не заметил :(

2017-03-14 11:58 UTC, galaxie commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +-type rule() ::
Ну я такой типа, не моя задача на этот спринт. Клиент будет работать и без этих изменений

2017-03-15 12:57 UTC, arentrue commented
После переименовния `validator.mustache` в `validation.mustache` в `handler:rest_init/2` забыл соответственно переименовать вызов `get_validator/1`.

2017-03-15 13:05 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +            case prepare_param(Rules, Name, Value, Validator) of
Мне видится более логичным, перенести функции `request_param_info/2` и `prepare_param/4` в `validation` модуль. Таким образом, все данные и типы относящиеся к валидации, будут в `validation`, а не разбросаны между `api` и `validation` модулями. Кроме того сейчас `api:request_param_info/2` - экспортирован, но не используется вне `api` модуля, и при этом использует типы из `validation`, что выглядит странно.

2017-03-15 13:14 UTC, arentrue commented
Ещё общий вопрос: зачем state `handler`'а содержит _validator_?

В `handler` _validator_ используется только при обращении к `api` функциям, причём _OperationID_, по которому и выбирается `validator`, также передается в эти вызовы. Почему бы не убрать _validator_ из интерфейса `api`, а брать его по _OperationID_ уже внутри `api`, а лучше прямо в `valdation` (см. мой коммент по поводу переносу всей логики валидации из `api` в `vaidation` модуль)?

2017-03-15 13:50 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/api.mustache
> +map_violated_rule({required, _}) ->  not_found.
Получается, что `map_violated_rule/1` должен обладать знанием о validation rules, которые применяются в модулях валидации, а не в `api`, и которые, кстати, даже не типизированы, (что было бы полезно для такого применения, как тут: сами правила в одном модуле, маппинг ошибок в другом).

Вообще, по моему, было бы логичнее, делать mapping в валидаторе, отдавая типизированные ошибки из него.
Далее, сделать callback'и для кастомизации error message в зависимости от типа ошибки.

2017-03-27 13:17 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/validation.mustache
> +-type id() :: atom().
Как-то странно, что тип `id` validation pool'а из `schema_validator.mustache` объявляется в `validation.mustache`.

2017-03-27 13:19 UTC, arentrue commented
В остальном, пожалуй, аппрув.

2017-03-27 13:19 UTC, arentrue approved these changes

2017-03-28 18:25 UTC, arentrue approved these changes
Не смотря на пару минорных докопов, можно так мержить - я это могу сам доправить, когда ребэйзиться буду.

2017-03-28 18:25 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/server.mustache
> +-export_type([id/0]).
Минорный докоп: это же Id validation pool'а из schema_validator.mustache. Странно, что он в server.mustache объявляется.

2017-03-28 18:25 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/validation.mustache
> +    Code :: term(),
Вижу, что сюда http code пробрался, да, но, судя по всему, без него не обойтись тут и глаза мне не режет.

2017-03-28 18:25 UTC, arentrue commented on modules/swagger-codegen/src/main/resources/erlang-server/schema_validator.mustache
>  -export([validate/3]).
А она, вообще, где-нибудь вызывается?

Вроде, вот эта связка используется:
```erlang
Validator = schema_validation:get_vlidator(ID),
Validator(Json, Defname)
```

2017-03-28 18:33 UTC, merged